In [ ]:
import numpy as np

In [ ]:
arr_rand = np.array([8, 8, 3, 7, 7, 0, 4, 2, 5, 2])
print("Array:",arr_rand)

In [ ]:
# Positions where value > 5
index_gt5 = np.where(arr_rand > 5)
print("Positions where value > 5: ", index_gt5)


In [ ]:
# Take items at given index
arr_rand.take(index_gt5)

In [ ]:
# If value > 5, then yield 'gt5' else 'le5'
np.where(arr_rand > 5, 'gt5', 'le5')

In [ ]:
# Location of the max
print('Position of max value: ', np.argmax(arr_rand)) 
# Location of the min
print('Position of min value: ', np.argmin(arr_rand)) 


In [34]:
a = np.zeros([4, 4])
b = np.ones([4, 4])
print(a)
print(b)


[[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]
[[1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]]


In [35]:
# Vertical Stack Equivalents (Row wise)
np.concatenate([a, b], axis=0) 
np.vstack([a,b]) 
np.r_[a,b] 

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [38]:
# Horizontal Stack Equivalents (Coliumn wise)
np.concatenate([a, b], axis=1)
np.hstack([a,b]) 
np.c_[a,b]

array([[0., 0., 0., 0., 1., 1., 1., 1.],
       [0., 0., 0., 0., 1., 1., 1., 1.],
       [0., 0., 0., 0., 1., 1., 1., 1.],
       [0., 0., 0., 0., 1., 1., 1., 1.]])

In [39]:
np.r_[[1,2,3], 0, 0, [4,5,6]]


array([1, 2, 3, 0, 0, 4, 5, 6])

In [40]:
arr = np.random.randint(1,6, size=[8, 4])
arr

array([[1, 5, 3, 3],
       [3, 4, 3, 4],
       [3, 5, 2, 3],
       [4, 2, 4, 2],
       [2, 4, 3, 3],
       [3, 3, 5, 1],
       [1, 2, 2, 4],
       [5, 2, 4, 5]])

In [41]:
# Sort each columns of arr
np.sort(arr, axis=0)


array([[1, 2, 2, 1],
       [1, 2, 2, 2],
       [2, 2, 3, 3],
       [3, 3, 3, 3],
       [3, 4, 3, 3],
       [3, 4, 4, 4],
       [4, 5, 4, 4],
       [5, 5, 5, 5]])

In [42]:
x = np.array([1, 10, 5, 2, 8, 9])
sort_index = np.argsort(x)
print(sort_index)

[0 3 2 4 5 1]


In [43]:
x[sort_index]

array([ 1,  2,  5,  8,  9, 10])

In [44]:
# Argsort the first column
sorted_index_1stcol = arr[:, 0].argsort()
# Sort 'arr' by first column without disturbing the integrity of rows
arr[sorted_index_1stcol]

array([[1, 5, 3, 3],
       [1, 2, 2, 4],
       [2, 4, 3, 3],
       [3, 4, 3, 4],
       [3, 5, 2, 3],
       [3, 3, 5, 1],
       [4, 2, 4, 2],
       [5, 2, 4, 5]])

In [45]:
# Descending sort
arr[sorted_index_1stcol[::-1]]

array([[5, 2, 4, 5],
       [4, 2, 4, 2],
       [3, 3, 5, 1],
       [3, 5, 2, 3],
       [3, 4, 3, 4],
       [2, 4, 3, 3],
       [1, 2, 2, 4],
       [1, 5, 3, 3]])

In [46]:
# Sort by column 0, then by column 1
lexsorted_index = np.lexsort((arr[:, 1], arr[:, 0]))
arr[lexsorted_index]

array([[1, 2, 2, 4],
       [1, 5, 3, 3],
       [2, 4, 3, 3],
       [3, 3, 5, 1],
       [3, 4, 3, 4],
       [3, 5, 2, 3],
       [4, 2, 4, 2],
       [5, 2, 4, 5]])

In [47]:
# Create a datetime64 object
date64 = np.datetime64('2018-02-04 23:10:10')
date64

numpy.datetime64('2018-02-04T23:10:10')

In [48]:
# Drop the time part from the datetime64 object
dt64 = np.datetime64(date64, 'D')
dt64

numpy.datetime64('2018-02-04')

In [49]:
# Create the timedeltas (individual units of time)
tenminutes = np.timedelta64(10, 'm') # 10 minutes
tenseconds = np.timedelta64(10, 's') # 10 seconds
tennanoseconds = np.timedelta64(10, 'ns') # 10 nanoseconds
print('Add 10 days: ', dt64 + 10)
print('Add 10 minutes: ', dt64 + tenminutes)
print('Add 10 seconds: ', dt64 + tenseconds)
print('Add 10 nanoseconds: ', dt64 + tennanoseconds)


Add 10 days:  2018-02-14
Add 10 minutes:  2018-02-04T00:10
Add 10 seconds:  2018-02-04T00:00:10
Add 10 nanoseconds:  2018-02-04T00:00:00.000000010


In [50]:
# Convert np.datetime64 back to a string
np.datetime_as_string(dt64)

'2018-02-04'

In [53]:
print('Date: ', dt64)
print("Is it a business day?: ", np.is_busday(dt64)) 
print("Add 2 business days, rolling forward to nearest biz day: ", np.busday_offset(dt64, 2, roll='forward'))  
print("Add 2 business days, rolling backward to nearest biz day: ", np.busday_offset(dt64, 2, roll='backward')) 
#> Date: 2018-02-04
#> Is it a business day?: False
#> Add 2 business days, rolling forward to nearest biz day: 2018-02-07
#> Add 2 business days, rolling backward to nearest biz day: 2018-02-06

Date:  2018-02-04
Is it a business day?:  False
Add 2 business days, rolling forward to nearest biz day:  2018-02-07
Add 2 business days, rolling backward to nearest biz day:  2018-02-06
