In [8]:
list1 = [10,20,30,40]/2

TypeError: unsupported operand type(s) for /: 'list' and 'int'

In [2]:
import numpy as np

In [3]:
numpy = np.array([10,20,30,40])/2

In [4]:
numpy

array([ 5., 10., 15., 20.])

In [5]:
list2= [1,2,3,4] ** 2

TypeError: unsupported operand type(s) for ** or pow(): 'list' and 'int'

In [10]:
numpy1= np.array([1,2,3,4]) ** 2

In [11]:
numpy1

array([ 1,  4,  9, 16])

In [6]:
h = [1.67,1.89,1.56,1.68,1.78]

In [7]:
w= [66.2,45.3,67.8,89.5,56.1]

In [35]:
bmi= w/h**2

TypeError: unsupported operand type(s) for ** or pow(): 'list' and 'int'

In [36]:
h = np.array([1.67,1.89,1.56,1.68,1.78])

In [37]:
w = np.array([[66.2,45.3,67.8,89.5,56.1]])

In [38]:
bmi= w/h**2

In [39]:
bmi

array([[23.73695722, 12.68161586, 27.85996055, 31.71060091, 17.70609771]])