### 1)Import the numpy package under the name np

In [1]:
import numpy as np


 ### 2.Print the numpy version and the configuration

In [7]:
print(np.__version__)
np.show_config()

1.23.4
openblas64__info:
    library_dirs = ['D:\\a\\numpy\\numpy\\build\\openblas64__info']
    libraries = ['openblas64__info']
    language = f77
    define_macros = [('HAVE_CBLAS', None), ('BLAS_SYMBOL_SUFFIX', '64_'), ('HAVE_BLAS_ILP64', None)]
blas_ilp64_opt_info:
    library_dirs = ['D:\\a\\numpy\\numpy\\build\\openblas64__info']
    libraries = ['openblas64__info']
    language = f77
    define_macros = [('HAVE_CBLAS', None), ('BLAS_SYMBOL_SUFFIX', '64_'), ('HAVE_BLAS_ILP64', None)]
openblas64__lapack_info:
    library_dirs = ['D:\\a\\numpy\\numpy\\build\\openblas64__lapack_info']
    libraries = ['openblas64__lapack_info']
    language = f77
    define_macros = [('HAVE_CBLAS', None), ('BLAS_SYMBOL_SUFFIX', '64_'), ('HAVE_BLAS_ILP64', None), ('HAVE_LAPACKE', None)]
lapack_ilp64_opt_info:
    library_dirs = ['D:\\a\\numpy\\numpy\\build\\openblas64__lapack_info']
    libraries = ['openblas64__lapack_info']
    language = f77
    define_macros = [('HAVE_CBLAS', None), ('BLAS_SYMBO

### 3.Create a null vector of size 10

In [52]:
z=np.zeros(10)
print(z)

[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]


### 4.How to get the documentation of the numpy add function from the command
### line?

In [15]:
 "import numpy; numpy.info(numpy.add)"

'import numpy; numpy.info(numpy.add)'

 ### 5.Create a null vector of size 10 but the fifth value which is 1

In [22]:
z=np.zeros(10)
z[4]=1
print(z)

[0. 0. 0. 0. 1. 0. 0. 0. 0. 0.]


### 6.Create a vector with values ranging from 10 to 49

In [25]:
z=np.arange(10,50)
print(z)

[10 11 12 13 14 15 16 17 18 19 20 21 22 23 24 25 26 27 28 29 30 31 32 33
 34 35 36 37 38 39 40 41 42 43 44 45 46 47 48 49]


### 7.Reverse a vector (first element becomes last)

In [41]:
z=np.arange(50)
z=z[::-1]
z

array([49, 48, 47, 46, 45, 44, 43, 42, 41, 40, 39, 38, 37, 36, 35, 34, 33,
       32, 31, 30, 29, 28, 27, 26, 25, 24, 23, 22, 21, 20, 19, 18, 17, 16,
       15, 14, 13, 12, 11, 10,  9,  8,  7,  6,  5,  4,  3,  2,  1,  0])

### 8.Create a 3x3 matrix with values ranging from 0 to 8

In [42]:
z=np.arange(9).reshape(3,3)
print(z)

[[0 1 2]
 [3 4 5]
 [6 7 8]]


### 9. Find indices of non­zero elements from [1,2,0,0,4,0] 

In [43]:
nz=np.nonzero([1,2,0,0,4,0])
print(nz)

(array([0, 1, 4], dtype=int64),)


### 10.Create a 3x3 identity matrix

z=np.eye(3,3)
print(z)

### 11.Create a 3x3x3 array with random values

In [48]:
z=np.random.random((3,3,3,))
z

array([[[0.99391924, 0.22854607, 0.86978059],
        [0.65011947, 0.23197179, 0.17273757],
        [0.76951025, 0.21232859, 0.26785097]],

       [[0.05007266, 0.72916038, 0.59815449],
        [0.3003497 , 0.84608805, 0.01514722],
        [0.61358215, 0.85394903, 0.27826565]],

       [[0.29961587, 0.61095522, 0.43628852],
        [0.11787214, 0.79018546, 0.70644983],
        [0.35722415, 0.21054214, 0.74489536]]])

 ## 12.Create a 10x10 array with random values and find the minimum and maximum
### values

In [50]:
z=np.random.random((10,10))
zmin,zmax=z.min(),z.max()
zmin,zmax

(0.005858271109854707, 0.9833373308856383)